name: SEARX Docker Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
         platforms: all
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
         version: latest
      - name: login to docker hub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - name: build the docker image
        run: |
          BDATE=$(date +%d-%m-%Y) \
          && SEARX_GIT_VERSION="$(git describe --match "v[0-9]*\.[0-9]*\.[0-9]*" HEAD 2>/dev/null | awk -F'-' '{OFS="-"; $1=substr($1, 2); if ($3) { $3=substr($3, 2); }  print}')" \
          && VERSION_GITCOMMIT=$(echo $SEARX_GIT_VERSION | cut -d- -f2-4) \
          && LABEL_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
          && LABEL_VCS_REF=$(git rev-parse HEAD) \
          && TIMESTAMP_SETTINGS=$(git log -1 --format="%cd" --date=unix -- searx/settings.yml) \
          && TIMESTAMP_UWSGI=$(git log -1 --format="%cd" --date=unix -- dockerfiles/uwsgi.ini) \
          && docker buildx build --build-arg SEARX_GIT_VERSION="${SEARX_GIT_VERSION}" \
          --build-arg VERSION_GITCOMMIT="${VERSION_GITCOMMIT}" \
          --build-arg LABEL_DATE="${LABEL_DATE}" \
          --build-arg LABEL_VCS_REF="${LABEL_VCS_REF}" \ 
          --build-arg LABEL_VCS_URL="${GIT_URL}" \
          --build-arg TIMESTAMP_SETTINGS="${TIMESTAMP_SETTINGS}" \
          --build-arg TIMESTAMP_UWSGI="${TIMESTAMP_UWSGI}" \ 
          --push \
          --tag avpnusr/searx:latest --tag avpnusr/searx:$BDATE \
            --platform linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64,linux/ppc64le \
            --file ./Dockerfile .
